// Generated by https://quicktype.io

// https://app.quicktype.io/

// https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype

export interface IPersona {
  nombre: string;
  apellido: string;
  ciudad: string;
  email: string;
  avatar: string;
  sueldo: string;
}
